### ISSUE TITLE
POST请求data参数问题

### ISSUE THREAD

**Issue by frystamuzn** [guren-cloud/v-request#2]
官方的wx.request
data: {
        x: '',
        y: ''
}
可以成功传参

wx.vrequest
只有当
data: 'key=value' 才能成功传参

如果要像wx.request  POST多个key:value  该怎么办？

**Comment by safe-dog** [comment]
## 简单版
遍历data，解析成string：
``` js
data = {
x:"",
y:""
}

vrequest_data = ""
for (let k in data) {
vrequest_data += k;
vrequest_data += "=";
vrequest_data += encodeURIComponent(data[k]);
vrequest_data += "&";
}
```

## 复杂版
参考request模块：https://www.npmjs.com/package/request
以及v-request的data处理代码：https://github.com/guren-cloud/v-request/blob/master/v-request.js#L65
自行进行body数据协商处理~
