### ISSUE TITLE
responseType设置无效

### ISSUE THREAD

**Issue by geetor** [guren-cloud/v-request#3]
我将responseType设置为arrayBuffer后，返回的res.body仍然是字符串（设置的目的是获取图片的arrayBuffer -> 在本地js文件中调用'wx.arrayBufferToBase64()'来显示图片）
仔细研究之后，发现这与我所请求的地址是"HTTP"有关，不知该用什么方法规避呢？

**Comment by dilibili** [comment]
同问

**Comment by geetor** [comment]
> 同问

后来我将要request的链接改为"https"，换用官方的wx.request() -> 解决了这个问题

**Comment by safe-dog** [comment]
小程序端的responseType后端程序会自动忽略过滤~ 因为我们后端使用的是nodejs的request模块，使用方法和小程序端的不一样，可以参考request模块的用法，然后修改云开发的脚本即可实现：
https://npmjs.com/package/request
