### ISSUE TITLE
依赖的基础库版本是多少

### ISSUE THREAD

**Issue by A1014280203** [guren-cloud/v-request#5]
小程序需要通过基础库版本判断可以给哪些用户使用。版本低的用户是不能使用依赖高版本库的小程序的。希望作者注明一下。

**Comment by safe-dog** [comment]
你好，只要是能使用云开发的，都可以使用呢，小程序的云开发的版本需求就是这个库的最低依赖基础库，所以用了云开发环境，就不用担心基础库版本的
